"""Prompts export matching Deliverables layout."""
from app.prompts.resume_prompt import RESUME_EXTRACTION_SYSTEM_PROMPT, RESUME_EXTRACTION_USER_PROMPT
from app.prompts.job_prompt import JOB_EXTRACTION_SYSTEM_PROMPT, JOB_EXTRACTION_USER_PROMPT
from app.prompts.gap_prompt import SKILL_GAP_SYSTEM_PROMPT, SKILL_GAP_USER_PROMPT
from app.prompts.evidence_prompt import EVIDENCE_SYSTEM_PROMPT, EVIDENCE_USER_PROMPT
from app.prompts.recruiter_prompt import RECRUITER_SYSTEM_PROMPT, RECRUITER_USER_PROMPT

__all__ = [
    "RESUME_EXTRACTION_SYSTEM_PROMPT",
    "RESUME_EXTRACTION_USER_PROMPT",
    "JOB_EXTRACTION_SYSTEM_PROMPT",
    "JOB_EXTRACTION_USER_PROMPT",
    "SKILL_GAP_SYSTEM_PROMPT",
    "SKILL_GAP_USER_PROMPT",
    "EVIDENCE_SYSTEM_PROMPT",
    "EVIDENCE_USER_PROMPT",
    "RECRUITER_SYSTEM_PROMPT",
    "RECRUITER_USER_PROMPT",
]

