import { NavLink } from 'react-router-dom'
import { BarChart3, BriefcaseBusiness, ChevronLeft, FileText, GitCompare, LayoutDashboard, PanelLeft, Plus, Settings, Sparkles, Users } from 'lucide-react'

const links = [{ to: '/', label: 'Overview', icon: LayoutDashboard }, { to: '/resumes', label: 'Resumes', icon: FileText }, { to: '/jobs', label: 'Jobs', icon: BriefcaseBusiness }, { to: '/ranking', label: 'Candidate ranking', icon: BarChart3 }, { to: '/compare', label: 'Compare', icon: GitCompare }]

export default function Sidebar({ open, onClose }) {
  return <aside className={`fixed inset-y-0 left-0 z-30 flex w-64 flex-col border-r bg-white p-5 transition-transform lg:static lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
    <div className="mb-10 flex items-center justify-between"><NavLink to="/" className="flex items-center gap-2.5 text-lg font-extrabold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-ink text-white"><Sparkles size={18} /></span>Hire<span className="text-teal">Lens</span></NavLink><button className="text-muted lg:hidden" onClick={onClose}><ChevronLeft size={20} /></button></div>
    <p className="eyebrow mb-3 px-3">Workspace</p><nav className="space-y-1">{links.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} onClick={onClose} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition ${isActive ? 'bg-mint text-teal' : 'text-muted hover:bg-canvas hover:text-ink'}`}><Icon size={18} strokeWidth={1.8} />{label}</NavLink>)}</nav>
    <div className="mt-8 border-t pt-7"><p className="eyebrow mb-3 px-3">Manage</p><NavLink to="/jobs/create" onClick={onClose} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-muted hover:bg-canvas hover:text-ink"><Plus size={18} />Create a job</NavLink><button className="mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-muted hover:bg-canvas hover:text-ink"><Settings size={18} />Settings</button></div>
    <div className="mt-auto rounded-2xl bg-ink p-4 text-white"><div className="mb-3 flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/10"><Users size={16} /></span><span className="text-xs font-bold">Recruiter plan</span></div><p className="mb-3 text-[11px] leading-5 text-white/60">You have 8,420 screening credits left.</p><div className="h-1.5 overflow-hidden rounded-full bg-white/15"><div className="h-full w-2/3 rounded-full bg-teal" /></div></div>
  </aside>
}